UCLA scl 1.0
NumRows : 20
CoreRow Horizontal
 Coordinate : 0
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 1
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 2
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 3
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 4
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 5
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 6
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 7
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 8
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 9
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 10
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 11
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 12
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 13
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 14
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 15
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 16
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 17
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 18
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
CoreRow Horizontal
 Coordinate : 19
 Height : 1
 Sitewidth : 1
 Sitespacing : 1
 Siteorient : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites : 20
End
